function [IndexList,out] = Check_Word_Indices(word,Board,dimension,coords);

% Find every set of indices that correspond to a word

for ijk=1:length(word)  
     checks = strcmp(Board,word(ijk));   
    % begin looping over every 'root' letter    
    idxs = find(checks==1);
    IndexList(ijk).idxs=idxs;
end

if length(word) == 3
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs);
elseif length(word) == 4
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs);
elseif length(word) == 5
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs);
elseif length(word) == 6
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs);
elseif length(word) == 7
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(7).idxs);
elseif length(word) == 8
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(8).idxs);  
elseif length(word) == 9
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(8).idxs,IndexList(9).idxs);   
elseif length(word) == 10
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(8).idxs,IndexList(9).idxs,...
IndexList(10).idxs);   
elseif length(word) == 11
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(8).idxs,IndexList(9).idxs,...
IndexList(10).idxs,IndexList(11).idxs);     
elseif length(word) == 12
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(8).idxs,IndexList(9).idxs,...
IndexList(10).idxs,IndexList(11).idxs,IndexList(12).idxs); 
elseif length(word) == 13
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(8).idxs,IndexList(9).idxs,...
IndexList(10).idxs,IndexList(11).idxs,IndexList(12).idxs,...
IndexList(13).idxs);    
elseif length(word) == 14
out = CombVec(IndexList(1).idxs,IndexList(2).idxs,...
IndexList(3).idxs,IndexList(4).idxs,IndexList(5).idxs,...
IndexList(6).idxs,IndexList(8).idxs,IndexList(9).idxs,...
IndexList(10).idxs,IndexList(11).idxs,IndexList(12).idxs,...
IndexList(13).idxs,IndexList(14).idxs);   
end
out=out';

